version: "3"

services:
  app:
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/dev.Dockerfile
    ports:
      - "80:80"
    command:
      [
        "CompileDaemon",
        "-directory=./src",
        "-build=go build -o ../bin/server",
        "-command=./bin/server",
      ]
    volumes:
      - ../:/usr/src/app
